### ISSUE TITLE
1° Encontro

### ISSUE THREAD

**Issue by ferfabricio** [react-maringa/react-101#1]
Galera, por onde devemos começar?

**Comment by andreloty** [comment]
definindo local e data?

**Comment by ferfabricio** [comment]
@andreloty Não seria melhor definir o que vamos tratar / estudar e acharmos um "mentor" para esse primeiro encontro, daí sim definir local e data?

**Comment by andreloty** [comment]
minha (minúscula) experiência diz que "se não tem data pra acontecer, nunca vai acontecer"...
a partir do momento que se definem as datas, já se tem noção de prazo...
tendo prazo, se tem prioridades...
se tem prioridades, a galera corre atrás...

mas isso é apenas a minha opinião...

**Comment by ferfabricio** [comment]
08/11?

**Comment by geovanisouza92** [comment]
Bom, local já sabem que a casa (Serrabits) tá sempre disponível se quiser.

Sobre a data, não acha melhor deixar pra semana seguinte? (vai rolar o DevFest na semana)

**Comment by andreloty** [comment]
@geovanisouza92 vc diz no dia 15/11?

**Comment by ferfabricio** [comment]
Dia 15 é feriado, eu tava pensando como nesses encontros iniciais deve ter menos gente reunida de já ir fazendo o mais breve possível.
Essa semana temos feriado e na depois do devfest tambem temos feriado.

**Comment by otaviolarrosa** [comment]
@ferfabricio 
Pode rolar um hangout também ?
Estou em Curitiba, de mudança... Ia ser MaraviWonderfull pra mim.

**Comment by andreloty** [comment]
tem que ser durante a semana, certo?
se possível, quarta ou sexta...
como dia 15/11 (quarta) será feriado, por que não no dia 17/11?
quanto aos palestrantes...
temos pessoas bacanas aqui em maringá pra falar sobre isso, certo?
como eu tou começando agora com reactjs, não conheço o povo que manja...

**Comment by ferfabricio** [comment]
@andreloty eu vou arrumar alguém para falar nesse primeiro encontro, nem que for por conferência, deixa comigo!

Eu to vendo com o Marcos Florêncio (@eptaccio) se conseguimos fazer na Tecnospeed esse primeiro encontro, porém na semana do dia 20/11

**Comment by ferfabricio** [comment]
Galera, tivemos confirmação do local e data:
21/11 19h30 na Tecnospeed

Vou marcar no meetup.com

**Comment by ferfabricio** [comment]
Sugestões de tópicos:
- O que tem de diferente de outros frameworks?
- O React disponibiliza conceitos novos?

**Comment by andreloty** [comment]
eu não sei se terão muitos estudantes de faculdades que acompanharão os encontros, mas eu acho no meio da semana complicado por uma série de fatores...
se bem que entraremos em período de férias, mas caso esse evento se consolide (o que eu espero que aconteça), é possível que os próximos encontros sejam no final de semana?

**Comment by andreloty** [comment]
sobre os tópicos, meus pitacos:

- ReactJs é bom só pra startups e projetos pequenos e "hypsters" ou também pode ser usado por grandes empresas em projetos grandes e complexos?
- Cases de uso do ReactJs em grandes empresas
- Como podemos convencer nossos líderes técnicos a usar o ReactJs

**Comment by jhms** [comment]
Boa tarde Senhores.

Há algum custo? Está liberado para entusiastas? 
Meus conhecimentos são básicos na área da informática, ainda mais sobre o ReactJs. 

Agradeço desde já

**Comment by ferfabricio** [comment]
@jhms Não tem custo, somente pedimos que seja feita a inscrição pelo [Meetup do React Maringá](https://www.meetup.com/React-Maringa/events/244970847/?_locale=pt-BR) para nós termos uma noção da quantidade de participantes.
