### ISSUE TITLE
10º React Maringá #C4P

### ISSUE THREAD

**Issue by wwwflorencio** [react-maringa/react-101#10]
# React Maringá
Salve galera, estamos indo para o decimo encontro agora dia 16/06 e vamos usar essa issue para submissão de palestras.

Inscrições gratuitas em:
-embreve-

## Formato para submeter palestras
**Nome**
Enzo

**Twitter (se tiver)**
enzouser

**Título ou tema da palestra**
Exemplo de título

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

----

O evento é da comunidade para a comunidade, contamos com sua submissão, **todos tem espaço para falar** ✌️

**Comment by frontendwizard** [comment]
**Nome**
Juliano Rafael

**Twitter**
[julianorsfarias](https://twitter.com/julianorsfarias)

**Título ou tema da palestra**
Prototipando na velocidade da luz com Expo

**Comment by JoaoAntonioMaruti** [comment]
**Nome**
João Antonio Maruti Milagres

**Título ou tema da palestra**
Como é a experiência de desenvolvimento com react-native
