### ISSUE TITLE
2° Encontro

### ISSUE THREAD

**Issue by wwwflorencio** [react-maringa/react-101#2]
Então galera, conforme combinado no primeiro evento #1 o segundo encontro ficou combinado para semana que vem no dia 28/11.

[Que for, por favor confirme presença nesse link :)](https://www.meetup.com/pt-BR/React-Maringa/events/245310825/?eventId=245310825)

Como combinado também, nesse segundo evento vamos trabalhar com light talks (pequenas apresentações) em assuntos pré selecionados, sendo esses:

- [x] ES5/ES6 
- [x] webpack
- [ ] CSS dentro do js
- [ ] graphql
- [ ] jest 
- [ ] react-create-app
- [ ] boiraplates
- [ ] redux
- [ ] SSR
- [ ] Storybook

Para ficar mais fácil, quem estiver disposto a compartilhar conhecimento comente aqui nessa issue seguindo o modelo:
------------------------
**Nome**
Marcos

**Título da talk**
Foguetes com react

**Descrição**
Como construir um foguete com react 

------------------------
Se tiver alguma sugestão para o próximo encontro, comente nessa issue também :)

**Comment by lucasghelal** [comment]
Fala galera!! 

Tudo certo para amanhã? Como estão pensado em conduzir o nosso encontro?

**Comment by rodrigoAOliveira** [comment]
Tem algum custo para participar do evento?

**Comment by wwwflorencio** [comment]
@LucasHelal opa, tudo certo sim. Estamos planejando dessa vez termos pequenas apresentações de assuntos especificos 😄

**Comment by wwwflorencio** [comment]
@rodrigoAOliveira não, é só se [ inscrever nesse link](https://www.meetup.com/pt-BR/React-Maringa/events/245310825/?eventId=245310825) e aparecer no dia

**Comment by lucasghelal** [comment]
@rodrigoAOliveira, Copiando a resposta do @ferfabricio na Issue #1 

"Não tem custo, somente pedimos que seja feita a inscrição pelo[ Meetup do React Maringá](https://www.meetup.com/pt-BR/React-Maringa/events/245310825/?eventId=245310825) para nós termos uma noção da quantidade de participantes."

**Comment by ferfabricio** [comment]
Os itens restantes desta task foram migrados para #3
