### ISSUE TITLE
3º Encontro

### ISSUE THREAD

**Issue by ferfabricio** [react-maringa/react-101#3]
Vamos continuar nos itens levantados na issue #2 

- [x]  ES5/ES6
- [x]  webpack
- [ ]  create-react-app
- [ ]  boilerplates
- [ ]  CSS dentro do js
- [ ]  jest
- [ ]  redux
- [ ]  graphql
- [ ]  SSR
- [ ]  Storybook

**Comment by ferfabricio** [comment]
Nesse encontro eu vou dar um overview sobre como um componente React funciona e como criar seu primeiro componente utilizando o create-react-app

Daí num próximo evento o Leonardo vai começar um projeto integrando uma API graphQL.

**Comment by wwwflorencio** [comment]
Link para inscrição sem **custo nenhum**:
https://www.meetup.com/pt-BR/React-Maringa/events/245558463/
