### ISSUE TITLE
6º Encontro

### ISSUE THREAD

**Issue by ferfabricio** [react-maringa/react-101#6]
Vamos ao nosso 6º encontro no dia 06/02 na Tecnospeed.

Assuntos que já abordamos ou queremos abordar futuramente:

- [x]  ES5/ES6
- [x]  webpack
- [x]  create-react-app
- [x]  boilerplates
- [x]  CSS dentro do js
- [x]  jest
- [ ]  redux
- [ ]  graphql
- [ ]  SSR
- [ ]  Storybook

**Comment by luizaugustocs** [comment]
Nome
Luiz Augusto C. Souza

Título da talk
Como estilizar componentes react
