### ISSUE TITLE
8º Encontro - C4P

### ISSUE THREAD

**Issue by wwwflorencio** [react-maringa/react-101#8]
# React Maringá
Salve galera, estamos indo para o oitavo encontro agora dia 13/03 e vamos usar essa issue para submissão de palestras.

Evento gratuito, faça sua inscrição em:
https://www.meetup.com/pt-BR/React-Maringa/events/248446500/

## Formato para submeter palestras
**Nome**
Enzo

**Twitter (se tiver)**
enzouser

**Título ou tema da palestra**
Exemplo de título

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

----

O evento é da comunidade para a comunidade, contamos com sua submissão, **todos tem espaço para falar** ✌️

**Comment by ferfabricio** [comment]
**Nome**
Fernando Fabricio dos Santos

**Twitter**
[ferfabricio](https://twitter.com/ferfabricio)

**Título ou tema da palestra**
Construindo uma API GraphQL
