### ISSUE TITLE
9º React Maringá #C4P

### ISSUE THREAD

**Issue by wwwflorencio** [react-maringa/react-101#9]
# React Maringá
Salve galera, estamos indo para o nono encontro agora dia 10/04 e vamos usar essa issue para submissão de palestras.

Inscrições gratuitas em:
https://www.meetup.com/pt-BR/React-Maringa/events/248789027/

## Formato para submeter palestras
**Nome**
Enzo

**Twitter (se tiver)**
enzouser

**Título ou tema da palestra**
Exemplo de título

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

----

O evento é da comunidade para a comunidade, contamos com sua submissão, **todos tem espaço para falar** ✌️

**Comment by frontendwizard** [comment]
**Nome**
Juliano Rafael

**Twitter**
@julianorsfarias

**Título**
React Native: Porquê e Como?
